EmuKit/emukit

emukit/multi_fidelity/models/non_linear_multi_fidelity_model.py, tests/emukit/multi_fidelity/test_non_linear_models.py
Add ARD option for creating non-linear multi-fidelity model kernels.
I'm not sure whether we should inherit ARD name from GPy, or choose something that is a bit clearer?
=> Add ARD option for non-linear kernel

emukit/core/loop/loop_state.py
Changed return type of `create_loop_state` from `None` to `LoopState`. Moved function to end of file so `LoopState` class is already defined when using type annotation.
=> Fix return type

doc/conf.py, readthedocs.yml, requirements/doc_requirements.txt
*Issue #, if available:* #12 
*Description of changes:* RTD build required quite a few tweaks. Result can be found at https://emukit.readthedocs.io/en/apaleyes-rtd
=> Enable documentation hosting on RTD

emukit/core/interfaces/models.py
Return type was wrong for `IModel.predict`. This PR corrects that and expands the docstring.
=> Fix return type of predict in IModel interface

emukit/core/loop/outer_loop.py, tests/emukit/core/test_outer_loop.py
This PR makes sure the model is up to date with all observations at the end of the loop. 
Not sure if we should actually do this so would like other people's opinion. If the model training takes a long time and we are sure that we don't need the model to be up to date we would not want to do this but in most cases it seems a sensible thing to do.
=> Update model at the end of the loop

integration_tests/emukit/bayesian_optimization/test_local_penalization_loop.py
This test seems to be flaky as we run into linear algebra errors during the GP hyperparameter optimization. I fix the likelihood variance of the model and fix the random seed in this PR in an attempt to make it less flaky.
=> Make test less flaky

emukit/core/loop/model_updaters.py, emukit/examples/cost_sensitive_bayesian_optimization_loop.py, tests/emukit/core/test_loop_steps.py
Currently the cost model in the cost sensitive loop is trained on "Y" values whereas it should be trained on "cost" values. This PR fixes that. 
=> Allow model updater to update from any field in loop state

requirements/requirements.txt, requirements/test_requirements.txt
Address issue #100. Installs GPy with matplotlib dependencies to avoid import error.
=> install gpy plotting dependencies

.gitattributes
*Description of changes:* Currently our repo is reported as 96% Jupyter notebook, while we should be recognized as a Python lib. This change removes notebook files from the statistics. Sources: https://github.com/github/linguist/issues/3316, https://github.com/soniclavier/bigdata-notebook/blob/master/.gitattributes
=> Added attribute to fix language stats on GitHub

emukit/bayesian_optimization/local_penalization_calculator.py, emukit/core/categorical_parameter.py, emukit/core/continuous_parameter.py, emukit/core/discrete_parameter.py, emukit/core/parameter.py, emukit/core/parameter_space.py, tests/emukit/core/test_parameter_space.py, tests/emukit/test_acquisitions.py
Add get_bounds method to parameter space instead of having to convert to gpyopt design space.
=> Add get_bounds method

emukit/core/optimization/acquisition_optimizer.py, emukit/core/optimization/multi_source_acquisition_optimizer.py
*Issue #, if available:* #151
*Description of changes:* Correction to comment, we actually return the negative of the acquisition value at the optimum rather than the acquisition value itself.
=> Fix comment about acquisition optimizer return values

emukit/core/loop/outer_loop.py
*Description of changes:* The loop current updates the models twice per iteration. I think the cause of this was a simple white space error - the final model update should be done outside the for loop.
=> Don't update models twice per iteration

emukit/quadrature/methods/vanilla_bq.py, emukit/test_functions/quadrature_functions.py, tests/emukit/quadrature/test_rbf_quadrature_kernel.py, tests/emukit/quadrature/test_vanilla_bq.py
1. a bug fix in circular_gaussian test function
2. integrate method of vanilla BQ returns tuple of two floats now instead of tuple of float and 1x1 array (I thought it did that before already...)
3. added shape and some type tests for quadrature kernel and integration model because of 2.
=> some fixes to BQ

emukit/examples/models/random_forest.py
This PR fixes two problems of the random forest (RF):
- At the moment the RF contains a python for loop to compute the prediction for each test point. However, sklearn allows to make batch prediction which is much more efficient.
- Besides that, right now the RF returns the standard deviation instead of the variance.
=> batch prediction ; return var instead of std

emukit/core/optimization/local_search_acquisition_optimizer.py, tests/emukit/core/optimization/test_local_search_acquisition_optimizer.py
Handle the edge case of empty neighbourhood of a discrete parameter.
The other parameters already handled it correctly. 
Occurs rarely in practice, but should not throw an error. 
=> Fix empty neighbourhood of local parameter, test this

emukit/examples/multi_fidelity_dgp/benchmarking_examples.ipynb, emukit/experimental_design/__init__.py, integration_tests/emukit/experimental_design/test_experimental_design_with_categorical.py, tests/emukit/experimental_design/test_model_free_designs.py
*Issue #, if available:* #214 
*Description of changes:* Since LatinDesign carries some additional dependencies, i propose we remove implicit import of it from experimental_design package. This way it can never be imported accidentally. 
=> Remove implicit import of LatinDesign

emukit/examples/gp_bayesian_optimization/single_objective_bayesian_optimization.py, integration_tests/emukit/bayesian_optimization/test_single_objective_bayesian_optimization.py
single_objective_bayesian_optimisation.py, used within the tutorial examples, seems to have a call to an attribute that no longer exists (perhaps part of old interface?). Removing that call appears to lead to the desired behaviour.
=> fix bug in interface of single_objective_bayesian_optimisation example

emukit/__version__.py
*Issue #, if available:* #216 
*Description of changes:* The Latin bug in installation is hurting emukit installation, so we need a new version with a fix out.
=> Update to version 0.4.6

.travis.yml
*Issue #, if available:* #199 
*Description of changes:* libomp was added because of a pytorch bug that now seems to be fixed. This PR removes the install.
=> Remove libomp

emukit/core/acquisition/integrated_acquisition.py
#236
Functionality to control all the MCMC parameters when defining an integrated acquisition function. 
=> Added control over MCMC parameters when calling the integrated acquisition

emukit/examples/fabolas/fabolas_loop.py
Fabolas currently transforms the fidelity space to a log scale, however, the fabolas model/acquisitions are expecting the fidelity pre-transform.
I have discussed this fix with @aaronkl 
=> Fix to feed raw (non-transformed) s to the model/acquisition

CONTRIBUTING.md
Updated the module name from pytests to pytest.
-
changed module name pytests to pytest
=> Typo fix in instructions how to contribute

emukit/__init__.py
Issue #251
Can now see version number like standard python package using
`import emukit`
`emukit.__version__`
=> version bug fix

emukit/core/loop/outer_loop.py, emukit/core/loop/stopping_conditions.py, notebooks/Emukit-tutorial-basic-use-of-the-library.ipynb, tests/emukit/core/test_loop_steps.py, tests/emukit/core/test_stopping_conditions.py
*Issue #, if available:* #273 
*Description of changes:* This implements logical operations on stopping conditions. Namely, we can now combine them with `&` (and) and `|` (or). Sadly, Python's `and` and `or` cannot be overloaded.
This also makes ability to accept a list of conditions in the loop redundant, so this option is removed.
=> Boolean operations for stopping conditions

emukit/core/optimization/local_search_acquisition_optimizer.py, emukit/core/optimization/random_search_acquisition_optimizer.py
*Issue #, if available:* #235 
*Description of changes:* to pick these numbers I've just looked at other optimization codes, and it seems that most of the time people just use 5 or 10 as reasonably small defaults.
=> Default values for some optimizers

notebooks/Emukit-tutorial-basic-use-of-the-library.ipynb
NA
- matplotlib imports and configuration at head of tutorial were misleading - all plotting preparation went unused in this notebook.
- SeqeuntialPointCalculator import and instantiation as `point_calculator` was misleading - it went unused vis a vis the OuterLoop BayesianOptimizationLoop instantiated with `acquisition` and `model`. 
=> removed unused matplotlib and SequentialPointCalculator logic

emukit/core/loop/outer_loop.py
NA
added context: dict={} as kwarg to OuterLoop.get_next_points() for the external evaluation mode
=> Allow context={} in OuterLoop.get_next_points()

emukit/samplers/mcmc_sampler.py, requirements/requirements.txt
*Issue #, if available:* #295
*Description of changes:* See PR https://github.com/amzn/emukit/pull/299 which highlighted the issue. MCMC output format has changed in emcee>3; now it returns a State rather than a list. State is backwards compatible with a list. Hence the code change that works with both.
*To test with two emcee versions:*
```
conda create --name test_emcee_3  
conda install -n test_emcee_3 pytest pytest-cov
source activate test_emcee_3
conda install pip
pip install "emcee>=3" 
python3 -c "import emcee; print(emcee.__version__)"  #!! must be 3x
pip install GPy matplotlib mock pyDOE pytest-lazy-fixture sobol_seq
python3 -m pytest -x --cache-clear
source deactivate test_emcee_3  
```
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> Change mcmc_sampler to be compatible with emcee 2x and 3x

emukit/core/loop/user_function.py, emukit/core/loop/user_function_result.py, tests/README.md, tests/emukit/core/test_user_function.py
NA
On top of the context-in-OuterLoop::get_next_points() PR, this implements the Callable mixin for UserFunction. It means you can do `user_function(x)` in addition to `user_function.evaluate(x)`
=> UserFunction(abc.ABC) -> UserFunction(abc.ABC, Callable)

emukit/core/optimization/context_manager.py, tests/emukit/core/optimization/test_context_manager.py
In context_manager: when considering multiple categorical variables in context, appending (instead of extending) the encodings will lead to the context_values being a sequence of lists and floats. This becomes an issue when expanding the vector at 
x_expanded[:, np.array(self.context_idxs).astype(int)] = self.context_values
because we are trying to assign a sequence to a list
changed append to extend in emukit.core.optimization.context_manager.py and added a corresponding test to show the bug
=> fixed context manager for multiple categorical variables in context

emukit/examples/fabolas/fmin.py
It seems that there was an artifact in the implementation of the fabolas optimizer in the given examples from a previous implementation of log-scale sampling of the dataset fraction. This is a small fix that removes the said artifact.
=> Fixed bug in examples/fabolas/fmin.py.

.gitignore, requirements/integration_test_requirements.txt
*Description of changes:* Recently all builds started failing. Error was in sensitivity notebook, and looked like this:
>TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>'
as a data type on that line
```
pd.DataFrame(d).plot(kind='bar',figsize=(12, 5))
```
This turned out to be incompatibility issue between numpy 1.20.0 and pandas 0.24.*. This shall hopefully fix it. Maybe we shall also get rid of pandas in this notebook, it's the only one using it?
Reference: https://github.com/numpy/numpy/issues/18355
=> Fix notebooks

emukit/model_wrappers/gpy_model_wrappers.py
*Issue #, if available:* #344
Fixes the referenced hyperparameter sampling issue by only adding random noise to the unfixed parameters before initiating HMC sampling.
=> Fixes GPyModelWrapper.generate_hyperparameters_samples changes the value of fixed parameters

emukit/model_wrappers/gpy_model_wrappers.py
*Issue #, if available:* #364
*Description of changes:* In the most recent version of GPy, 1.10.0, an API of one function was changed without backwards compatibility. This fix (and previous commit https://github.com/EmuKit/emukit/commit/90231e8c939ef645d0b1c492819eb8618e2213fb that I hastly fired away without proper PR) updates necessary APIs and bumps GPy version
=> More fixes of GPy updated API

emukit/model_wrappers/gpy_model_wrappers.py
*Issue:* #367 
The mentioned method `GPyModelWrapper.get_covariance_between_points()` is in fact more general than the doc-string implies. Updated the doc-string accordingly.
=> Update doc-string for get_covariance_between_points()

emukit/quadrature/methods/vanilla_bq.py, emukit/quadrature/methods/warped_bq_model.py, emukit/quadrature/methods/warpings.py, notebooks/Emukit-tutorial-Bayesian-quadrature-introduction.ipynb, notebooks/Emukit-tutorial-experimental-design-introduction.ipynb, tests/emukit/quadrature/test_warpings.py
- this is another pre-PR for #375 
- factored out the warping from warped Gaussian process. We had discussed that previously @apaleyes  but it hadn't made sense back then as there was only 1 warping and you cannot mix and match warpings with models. However, now we need another warping that will be used by at least 2 methods, and you anyways cannot mix and match in BQ, so here we go..
- some docstring unifications
- added and `update_parameters` method to the warping model (will need that later).
=> added square-root warping and factored out warpings in BQ

emukit/quadrature/interfaces/base_gp.py, emukit/quadrature/methods/vanilla_bq.py, emukit/quadrature/methods/warped_bq_model.py, emukit/quadrature/methods/warpings.py
Gradients:
- this is another pre-PR to #375 
- moved the gradients of the base-GP from the VanillaBQ class to the base GP where they belong. This wasn't an issue so far as VanillaBQ is basically the BaseGP just with a different API. This is still neater though, and will come in handy later.
Warpings (warping classes were introduced in PR #379 ):
- converted the base class of the warping to an abstract class. 
- the new parameter for the warping are now passed via keyword arguments. It is a bit more readable like this.
=> moving gradients of base GP to base GP class 

emukit/core/optimization/acquisition_optimizer.py, emukit/core/optimization/context_manager.py, tests/emukit/core/optimization/test_context_manager.py, tests/emukit/core/optimization/test_gradient_acquisition_optimizer.py
Problem addressed
---------------------
Previously, if an `AcquisitionOptimizer` received a categorical variable, it would incorrectly attempt to check whether the value was *in-domain*. It was assuming that the encoded value was being passed (of type `np.ndarray`). If passing a `str` category, this would fail, while passing a numerical category would lead to various (mostly wrong) outcomes, without warning.
Changes
---------
- It is now possible to use categorical variables in contexts. The `ContextManager` is now solely responsible for *in-domain* checks (for continuous parameters, raising warnings upon failure) and *in-encoding* checks (for categorical parameters, raising `ValueError` upon failure).
- Also changed `any` to `Any` in context type.
Related
--------
- Issue #359 could be …
=> Validate categorical variables when used in contexts 

emukit/bayesian_optimization/local_penalization_calculator.py, emukit/core/acquisition/integrated_acquisition.py, tests/emukit/core/test_acquisition.py
This PR fixes the following problem: IntegratedHyperParameterAcquisition.update_batches was not doing what it should, because it was calling update_batches on a newly-minted Acquisition object which it immediately threw away. Then, later Acquisition objects were not having update_batches applied to them. With this PR, update_batches saves its argument as an attribute, and a new method generate_acquisition_with_batch_update creates the Acquisition object and then calls update_batches on it with the values stored in the attribute.
=> Fix issue with creating IntegratedHyperParameterAcquisition objects

emukit/bayesian_optimization/acquisitions/entropy_search.py, emukit/bayesian_optimization/acquisitions/max_value_entropy_search.py, tests/emukit/test_acquisitions.py
*Issue #, if available:* #387
*Description of changes:* ES acquistion function turned out to be handling output shapes weirdly, which resulted in wrong shapes for the case when only one point was given as input. This PR fixes that, and adds few unit tests to validate shapes better.
=> Fix output dimensions of ES for 1 point input case

.github/workflows/codecov.yml, .github/workflows/tests.yml, CONTRIBUTING.md, setup.cfg
*Issue #, if available:* #340
*Description of changes:* We had some defaults for running pytest that were often getting in a way of running tests. Getting rid of them!
=> Remove confusing defaults for running tests

tests/emukit/quadrature/ground_truth_integrals_bounded_bq.py, tests/emukit/quadrature/test_quadrature_acquisitions.py, tests/emukit/quadrature/test_quadrature_kernels.py, tests/emukit/quadrature/utils.py
There was a a lot of duplicate code in the tests for `quadrature` acquisitions which made it hard to add a new acquisition function to the tests. This PR parameterize said tests. It is straightforward now to run all tests on a new acquisition function simply by adding a new fixture to the list.
Tests themselves are unchanged. 
=> Cleaning up acquisition tests in `quadrature`

tests/emukit/quadrature/test_measures.py
This PR parameterizes `quadrature` tests for integration measures and removes redundant code. This simplifies adding new measures to the tests an tests are more readble.
Tests themselves are unchanged.
=> Cleaning up integration measure tests in `quadrature`

emukit/model_wrappers/gpy_quadrature_wrappers.py, emukit/model_wrappers/sklearn_model_wrapper.py, emukit/quadrature/kernels/quadrature_brownian.py, tests/emukit/model_wrappers/test_gpy_wrappers_quadrature.py
GPy does not allow for Brownian motion offsets, but Emukit quadrature kernels do. Hence, when the GPy wrapper is used, we need to check if the offset is zero. This was a small bug. Added test to check this as well and some other tests.  
=> small fix in `quadrature` GPy wrapper

emukit/quadrature/kernels/__init__.py, emukit/quadrature/kernels/quadrature_brownian.py, emukit/quadrature/kernels/quadrature_kernels.py, emukit/quadrature/kernels/quadrature_matern32.py, emukit/quadrature/kernels/quadrature_matern52.py, emukit/quadrature/kernels/quadrature_rbf.py
There are several product quadrature kernels in the library which follow a similar structure. Hence code was dublicated. This PR introduces a `QuadratureProductKernel` base class which gets rid of the duplicted code. No functional changes. It might be possible to do all this prettier, but it's better than before. 
=> `QuadratureProductKernel` base class

emukit/bayesian_optimization/local_penalization_calculator.py
*Issue #, if available:* #421
*Description of changes:* Scipy minimize expects 1d inputs, and we were passing 2d for some unclear reason. Best part is that we were doing it intentionally, for no other reason, so the fix is just to remove a few symbols. Nice!
=> Fix scipy again

integration_tests/emukit/bayesian_optimization/test_constrained_loop.py
*Issue #421 , if available:* 
This PR sets a fixed numpy.random.seed for the flaky test mentioned in the issue. It seems to stop the flakiness. 
Still not entirely sure why it is flaky but it might be related to hyper-param optimization. In all the failed tests that I checked the lengthscale of the GP was very tiny for some reason (1e-300).
=> Fixing numpy seed in flaky test

emukit/test_functions/multi_fidelity/currin.py
*Issue #450*
*Description of changes:* Fixed typo in multi-fidelity test function Currin according to https://www.sfu.ca/~ssurjano/curretal91.html
=> Fixed typo in multi-fidelity test function Currin

.github/workflows/codecov.yml, .github/workflows/format.yml, .github/workflows/tests.yml, emukit/sensitivity/monte_carlo/monte_carlo_sensitivity.py, integration_tests/emukit/quadrature/test_wsabil_loop.py, requirements/requirements.txt, requirements/test_requirements.txt, setup.py, tests/emukit/model_wrappers/test_gpy_wrappers_quadrature.py, tests/emukit/multi_fidelity/test_kernels.py, tests/emukit/quadrature/test_measures.py, tests/emukit/quadrature/test_quadrature_acquisitions.py, tests/emukit/quadrature/test_quadrature_kernels.py, tests/emukit/quadrature/test_quadrature_models.py, tests/emukit/quadrature/test_warpings.py, tests/emukit/test_acquisitions.py
*Issue #, if available:* N/A but our build is broken
*Description of changes:* lazy-fixture is broken and probably won't be fixed: https://github.com/TvoroG/pytest-lazy-fixture/issues/65. This PR removes dependency on it from emukit.
=> Remove dependecy on lazy fixture

tests/emukit/quadrature/test_measures.py, tests/emukit/quadrature/test_warpings.py
Some pytest fixtures in `tests/emukit/quadrature/test_measures.py` got changed to instances in #460 by accident. Changing them back to fixtures. Plus correcting a typo. 
=> Small bugfix in tests.

.github/workflows/tests.yml, requirements/requirements.txt
*Issue #, if available:* #461
*Description of changes:* Instead of relying on GPy that hardcodes matplotlib version (which seems broken, see issue), let's install matplotlib separately. GPy, unfortunately, still requires matplotlib implicitly.
=> Install mpl differently, bring windows back

emukit/benchmarking/loop_benchmarking/benchmark_plot.py
The BenchmarkPlot does not correctly label the experiment loops colors or line styles in the legend
(Using Python 3.12.0 and matplotlib 3.10.0 and emukit 0.4.11). See issue here: https://github.com/EmuKit/emukit/issues/472#issuecomment-2644781883
I fixed the issue with just a few lines of code by setting up legend handles manually. In addition I added the option to set the y_axis to log scale which is the standard in literature for plotting regret.
=> feat: fixes benchmark plot legend, adds logy option
