EmuKit/emukit

examples/notebooks/Emukit-Bayesian-optimization-introduction.ipynb
Some of the formulae from this notebook didn't render properly in docs. This PR fixes that.
=> Some small changes to formulae so that it renders properly the docs

doc/index.rst, doc/usage.rst, emukit/core/loop/model_updaters.py, emukit/core/loop/outer_loop.py, emukit/core/loop/user_function.py, emukit/core/optimization/acquisition_optimizer.py
*Issue #, if available:* #20 
*Description of changes:* Added some logging in `emukit.core`, and a guide explaining by folks won't see it by default as well as how to see it. Once committed, this should serve as a base for everyone, so gradually our log coverage grows.
Example of the log output right now:
```
INFO:GP:initializing Y
INFO:GP:initializing inference method
INFO:GP:adding kernel and likelihood as parameters
INFO:emukit.core.loop.outer_loop:Starting outer loop
INFO:emukit.core.loop.outer_loop:Iteration 0
INFO:emukit.core.loop.model_updaters:Updating parameters of the model
INFO:emukit.core.optimization.acquisition_optimizer:Starting gradient-based optimization of acquisition function <class 'emukit.experimental_design.model_based.acquisitions.model_variance.ModelVariance'> …
```
=> Added basic logging

README.md
*Issue #, if available:* #12 
*Description of changes:* Added link to docs and playground
=> Updated documentation note in readme

emukit/experimental_design/model_based/acquisitions/integrated_variance.py, emukit/experimental_design/model_based/acquisitions/model_variance.py
*Description of changes:* `has_gradients` property decorator was missing from experimental design acquisition functions
=> Add property decorator

emukit/bayesian_optimization/interfaces/models.py
- Fix signatures so they agree with how they are called
- Add docstrings
=> Fixes for IEntropySearchModel interface

emukit/bayesian_optimization/acquisitions/acquisition_per_cost.py, emukit/bayesian_optimization/loops/bayesian_optimization_loop.py, emukit/core/loop/loop_state.py, emukit/core/loop/outer_loop.py, emukit/core/loop/user_function.py, emukit/core/loop/user_function_result.py, integration_tests/emukit/examples/test_cost_sensitive_bayesian_optimization.py, tests/emukit/core/test_loop_state.py
Changes to PR about cost sensitive loop based on feedback from Andrei 
=> Changes to cost sensitive loop

doc/emukit_structure.rst, emukit/bayesian_optimization/loops/bayesian_optimization_loop.py, emukit/core/loop/__init__.py, emukit/core/loop/candidate_point_calculators.py, emukit/examples/cost_sensitive_bayesian_optimization/cost_sensitive_bayesian_optimization_loop.py, emukit/examples/gp_bayesian_optimization/optimization_loops.py, emukit/experimental_design/model_based/experimental_design_loop.py, notebooks/Emukit-multi-fidelity-bayesian-optimization.ipynb, tests/emukit/core/test_loop_steps.py, tests/emukit/core/test_multi_source_optimizer.py, tests/emukit/core/test_outer_loop.py
=> Sequential -> SequentialPointCalculator

_posts/2016-06-09-experimental-design.markdown, _posts/2016-06-12-bayesian-optimization.markdown
*Description of changes:* corrections in the code of the examples
=> updating the examples of the BO and ED blogs

emukit/experimental_design/model_based/experimental_design_loop.py
*Description of changes:* Add model property to experimental design loop
=> Add model attribute to experimental design loop

emukit/__version__.py, setup.cfg
*Issue #, if available:* None
*Description of changes:* updated version number, added some metadata recommended for pipy package
=> Version bump

MANIFEST.in
=> Added manifest file (#124)

emukit/bayesian_optimization/loops/bayesian_optimization_loop.py, emukit/bayesian_optimization/loops/cost_sensitive_bayesian_optimization_loop.py, emukit/core/categorical_parameter.py, emukit/core/parameter_space.py, tests/emukit/bayesian_optimization/test_entropy_search.py, tests/emukit/conftest.py, tests/emukit/core/test_categorical_parameter.py, tests/emukit/core/test_encodings.py, tests/emukit/core/test_parameters.py
*Description of changes:* Somewhat surprised how I missed that implementation of categorical ignored rounding rules set by Encoding class. Tests are good!
=> Tests for categorical + some pep8 fixes

notebooks/Emukit-tutorial-basic-use-of-the-library.ipynb
*Issue #134 
adding BQ section to basics notebook
=> adding bq section to basics notebook

README.md, notebooks/index.ipynb
*Issue #, if available:* None
*Description of changes:*  Some minor stuff in readme, most importantly added a link to the website. Also changed all links to relative in the index notebook.
=> Updated lots of links

emukit/benchmarking/loop_benchmarking/benchmark_plot.py, tests/emukit/benchmarking/test_benchmark_plot.py
=> Covered BenchmarkPlot with tests

emukit/benchmarking/loop_benchmarking/benchmark_result.py, tests/emukit/benchmarking/test_benchmark_result.py
*Description of changes:* Other parts of benchmarking will be done in separate PRs
=> Tests for BenchmarkResult class

emukit/bayesian_optimization/acquisitions/entropy_search.py, emukit/bayesian_optimization/epmgp.py, emukit/samplers/__init__.py, emukit/samplers/mcmc_sampler.py, tests/emukit/bayesian_optimization/test_entropy_search.py, tests/emukit/bayesian_optimization/test_epmgp.py
*Issue #, if available:* #57 #58 
*Description of changes:* Moved files out of bayes_opt/util directory, and removed this dir as a result
=> Moved around mcmc samplers and epmgp

CONTRIBUTING.md, README.md, emukit/__version__.py, emukit/examples/README.md, notebooks/index.ipynb
*Description of changes:* Replaced all mentions of develop with master in preparation to branch renaming. Updated version
=> Preparing 0.4.1

emukit/core/loop/user_function.py, tests/emukit/core/test_user_function.py
- add tests for multi source function wrapper
- fix reordered outputs described in Issue #154 
- return cost if provided by source functions
=> Test and fix multi source function wrapper

README.md, doc/installation.rst
*Description of changes:* I've just realized our installation guides are out of date, so updated them, both in readme and in docs.
=> Updated installation guides

emukit/experimental_design/model_free/base.py
*Description of changes:* Removed one line that should have been removed with recent changes to model free designs
=> Removed obsolete line

emukit/multi_fidelity/models/non_linear_multi_fidelity_model.py, requirements/requirements.txt
Small change to non-linear model so that it continues to try to optimize at a new initial point if we get errors during the optimization, usually due to matrices becoming singular.
=> Use robust optimization flag

integration_tests/emukit/models/test_bohamiann.py, requirements/integration_test_requirements.txt
*Issue #, if available:* #164 
*Description of changes:* Add pip version of pybnn to reqs and remove skipping of tests.
=> Pybnn reqs

emukit/core/loop/candidate_point_calculators.py, emukit/core/optimization/acquisition_optimizer.py
*Description of changes:* All of a sudden found atleast_2d used, with a 2d argument!
=> Clarified optimizer output dims, removed atleast_2d usage

emukit/model_wrappers/gpy_model_wrappers.py
Allows user to do multiple restarts for optimization of hyper-parameters for gpy models
=> Add n_restarts option to gpy model wrapper

.travis.yml
*Issue #197* 
How mention @aaronkl I add ```brew install libomp```
=> fix-bug: fix #197: Add install of libomp

.travis.yml, requirements/requirements.txt
*Issue #, if available:* #119 
*Description of changes:* Updates GPy requirement to 1.9.8 (required to support python 3.7) and adds 3.7 build
=> Add python 3.7 build

CHANGELOG.md, emukit/__version__.py
Note that now we have changelog!
=> Preparing release 0.4.5

emukit/examples/multi_fidelity_dgp/benchmarking_examples.ipynb, emukit/test_functions/multi_fidelity/branin.py
*Issue #, if available:* #224 
*Description of changes:* This notebook should now replicate the experiments in the arxiv paper, before there were a couple of bugs.
=> Multi-fidelity dgp fixes

tests/emukit/examples/test_simple_gp_model.py
The test file name didn't start with "test" so didn't run before :S. I've also reduced the tolerances so it passes.
=> Rename test file so it actually runs

tests/emukit/test_acquisitions.py
added gradient test for mutual information acquisition 
=> adding bq acqusition test

CONTRIBUTING.md
There was a broken link to the license page.
I fixed the link to go to the license page. 
=> Fixed Broken Link

emukit/core/acquisition/integrated_acquisition.py, emukit/core/interfaces/models.py, emukit/model_wrappers/gpy_model_wrappers.py
*Description of changes:* fixed some leftovers from #241, namely the fact that we forgot to update the model interface with new parameters. Also some minor code style fixes
=> Fix samples interface

emukit/core/loop/outer_loop.py, emukit/core/loop/user_function_result.py
*Description of changes:* This commit adds logging to help users see intermediate state of the loop, and troubleshoot if necessary
=> Logging of suggested locations and user function outputs

notebooks/index.ipynb
I added a missing link for the ExpDesign tutorial to the notebook index. 
=> adding link of Exp design tutorial to index

README.md
*Description of changes:* citing information in README.md
=> Added citation info

emukit/bayesian_optimization/local_penalization_calculator.py, emukit/bayesian_optimization/loops/bayesian_optimization_loop.py, tests/emukit/bayesian_optimization/test_bayesian_optimization_loop.py, tests/emukit/bayesian_optimization/test_local_penalization.py, tests/emukit/bayesian_optimization/test_local_penalization_calculator.py
*Issue #, if available:* #220 
*Description of changes:* moved model validation where it belongs, thus fixing the issue above. also added a few tests, added few log lines and fixed test name typo
=> Added validation to LP calculator

CHANGELOG.md, emukit/__version__.py
*Description of changes:* release before NeurIPS 2019
=> Version update

emukit/core/loop/__init__.py, emukit/core/loop/outer_loop.py, emukit/core/loop/stopping_conditions.py, notebooks/Emukit-tutorial-basic-use-of-the-library.ipynb, tests/emukit/core/test_loop_steps.py
I have added in an convergence based stopping criterion. We can now tell the loop to stop if two consecutive queries are closer (in euclidean norm) than a user-specified value.
I have also added functionality to use multiple stopping criterion, e.g.specifying  a convergence and max number of steps for the optimization. The loop will stop when any criterion is triggered.
This is demonstrated in Emukit-tutorial-basic-use-of-the-library.ipynb .
=> Additional stopping functionality

emukit/quadrature/kernels/quadrature_rbf.py, emukit/test_functions/quadrature/__init__.py, emukit/test_functions/quadrature/hennig2D.py, tests/emukit/test_functions/test_hennig2d.py
an addition test function for BQ and a shape test
=> additional test function for BQ

emukit/examples/multi_fidelity_dgp/malaria_data_example.ipynb
*Description of changes:* found few typos as I was reading throught the deep GP malaria notebook
=> Fixed few typos in Malaria notebook

emukit/core/constraints.py, integration_tests/emukit/bayesian_optimization/test_constrained_loop.py, tests/emukit/core/test_constraints.py
*Issue #, if available:* #288 
*Description of changes:* Fixed the bug, added some validation and more tests
=> Fixed dimensionality issues in LinearInequalityConstraint implementation

emukit/examples/fabolas/fabolas_loop.py, emukit/examples/fabolas/fmin.py
small changes to Fabolas to account for updated interfaces
=> small fixed to Fabolas

emukit/core/__init__.py, emukit/core/bandit_parameter.py, tests/emukit/core/test_parameters.py
NA
Parameter that represents a subset of the full Cartesian product of its subparameters.
Needs tests and an associated acquisition optimizer change (optimizing on the latent full Cartesian product of subparameters and rounding to nearest element of the valid subset is no bueno) before merge, but the Parameter implementation is ready for review.
=> BanditParameter implementation

tests/emukit/bayesian_optimization/test_local_penalization.py, tests/emukit/bayesian_optimization/test_multipoint_expected_improvement.py, tests/emukit/multi_fidelity/test_non_linear_models.py
*Issue #, if available:* #316 
*Description of changes:* Turned out to be some inaccuracies with dimensions. Tested with both scipy 1.4.1 and 1.5.1, tests pass
=> Fix dimentionality issues with scipy

emukit/bayesian_optimization/acquisitions/max_value_entropy_search.py
Fixed Gumbel sampler subroutine for MES and MUMBO.
We now fit the Gumbel (minima) distribution instead of the Gumbel (maxima) distribution, which is what we require for function minimisation.
I have also added some comments explaining where the equations come from to avoid future confusions on this issue.
=> fixed gumbel sampler bug

emukit/bayesian_optimization/acquisitions/max_value_entropy_search.py
Fixing Issue  331
https://github.com/EmuKit/emukit/issues/331
=> bug fix in MUMBO

.github/workflows/tests.yml
*Issue #, if available:* #340
*Description of changes:* trying 3.8 build, to see if it works
=> Let's try 3.8 python build

emukit/core/acquisition/integrated_acquisition.py
*Issue #, if available:* #363
*Description of changes:* parameters are now properly carried over to the update method
=> Use same settings to update samples

.github/workflows/tests.yml, integration_tests/emukit/notebooks/test_notebooks.py
*Description of changes:* with new GPy version out, let's try running python 3.9 
=> Trying build on 3.9

emukit/core/constraints.py
=> Updating constraints docstrings to correctly indicate closed interval

.github/workflows/codecov.yml, .github/workflows/tests.yml, CONTRIBUTING.md, README.md, doc/index.rst, doc/installation.rst, emukit/examples/README.md, notebooks/index.ipynb, setup.py
*Issue #, if available:* #348
*Description of changes:* Turned out we had lots of links that were referring to the branch. Also discovered some outdated links to "amzn" org.
=> Master -> main, amzn -> emukit

emukit/quadrature/acquisitions/uncertainty_sampling.py
*Issue #377 
- this is needed for the draft PR #375 
- added power to density
- adjusted the gradient
- some docstring fixes.
*tests*
- ran pytest and gradients seem to be correct still.
=> Adding power to measure in uncertainty sampling for BQ

notebooks/Emukit-tutorial-basic-use-of-the-library.ipynb, requirements/requirements.txt
(1) Correcting a few typos and other minor errors in a tutorial.
(2) Adding torch to requirements.txt - this is required to run the code in emukit/examples.
=> Fix typos in tutorial, and add torch to requirements

emukit/core/bandit_parameter.py, emukit/core/optimization/local_search_acquisition_optimizer.py, tests/emukit/core/test_parameters.py
*Issue #, if available:* #302
*Description of changes:* Updated some code that was causing deprecation warnings.
=> Fix code that triggered numpy warnings

.github/workflows/format.yml, .github/workflows/tests.yml
*Description of changes:* Moved all formatting checks to a separate action file
=> Separated formatting checks

emukit/quadrature/interfaces/standard_kernels.py, tests/emukit/quadrature/test_quadrature_kernels.py
Added long overdue gradient tests for the kernel embeddings in the `quadrature` package. And some minor docstring formatting. 
=> Gradient tests for `quadrature` kernel embeddings.

emukit/examples/vanilla_bayesian_quadrature_with_rbf/vanilla_bq_loop_with_rbf.py, emukit/model_wrappers/gpy_quadrature_wrappers.py, emukit/quadrature/__init__.py, emukit/quadrature/acquisitions/uncertainty_sampling.py, emukit/quadrature/interfaces/standard_kernels.py, emukit/quadrature/kernels/quadrature_kernels.py, emukit/quadrature/kernels/quadrature_matern32.py, emukit/quadrature/kernels/quadrature_rbf.py, emukit/quadrature/loop/bayesian_monte_carlo_loop.py, emukit/quadrature/loop/point_calculators/quadrature_point_calculators.py, emukit/quadrature/loop/vanilla_bq_loop.py, emukit/quadrature/measures/domain.py, emukit/quadrature/measures/gaussian_measure.py, emukit/quadrature/measures/integration_measure.py, emukit/quadrature/measures/uniform_measure.py, emukit/quadrature/methods/warped_bq_model.py, emukit/quadrature/typing.py
- Had forgotten the `quadrature` GPy wrapper docs in #412 .
- Introduced `BoundsType` for the integration bounds to avoid copy paste errors.
- no functional changes.
=> GPy `quadrature` wrapper docs

emukit/quadrature/kernels/quadrature_kernels.py, tests/emukit/quadrature/ground_truth_integrals_qkernel.py, tests/emukit/quadrature/test_measures.py, tests/emukit/quadrature/test_quadrature_kernels.py
Tests for classmethods introduced in #423 (had forgotten to commit this).
=> Tests for some `quadrature` kernel classmethods

emukit/quadrature/interfaces/standard_kernels.py, emukit/quadrature/kernels/quadrature_brownian.py, emukit/quadrature/measures/domain.py, emukit/quadrature/measures/gaussian_measure.py, emukit/quadrature/measures/lebesgue_measure.py, emukit/quadrature/methods/bounded_bq_model.py
Some broken links and some missing `raises`.
=> Some doc fixes for `quadrature`

emukit/bayesian_optimization/acquisitions/negative_lower_confidence_bound.py, emukit/core/loop/outer_loop.py
=> Few small fixes

emukit/examples/multi_fidelity_dgp/benchmarking_examples.ipynb
*Issue #, if available:* #441
*Description of changes:* fix wrong import
=> Fix import of latin design

doc/emukit_structure.rst, setup.cfg
*Description of changes:* Coverage reports started counting examples for some reason, this PR fixes it
=> Fixing coverage report
